const India = {

  "Locations": [
  {
    "city": "Delhi", 
    "lat": "28.6600", 
    "lng": "77.2300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Delhi", 
    "capital": "admin", 
    "population": "29617000", 
    "population_proper": "16753235",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Delhi_India_Government.jpg/1200px-Delhi_India_Government.jpg"
  }, 
  {
    "city": "Mumbai", 
    "lat": "18.9667", 
    "lng": "72.8333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "admin", 
    "population": "23355000", 
    "population_proper": "12478447",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZz5_EgRHiNuhEuJhBLBX-Q4znz1X1YglelBud_OINdnHvRz66BGCQSkM8JpSu_myR9xc&usqp=CAU"
  }, 
  {
    "city": "Kolkāta", 
    "lat": "22.5411", 
    "lng": "88.3378", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "admin", 
    "population": "17560000", 
    "population_proper": "4496694",
    "image": "https://www.tripsavvy.com/thmb/Sr5pBQXwkv0ySso86xGn3LVScck=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1604382401-6724c1b48b17440fa316c194d777151b.jpg" 
  }, 
  {
    "city": "Bangalore", 
    "lat": "12.9699", 
    "lng": "77.5980", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "admin", 
    "population": "13707000", 
    "population_proper": "8443675",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Bangalore_.jpg/2560px-Bangalore_.jpg"
  }, 
  {
    "city": "Chennai", 
    "lat": "13.0825", 
    "lng": "80.2750", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "admin", 
    "population": "11324000", 
    "population_proper": "6727000",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/32/Chennai_Central.jpg"
  }, 
  {
    "city": "Hyderābād", 
    "lat": "17.3667", 
    "lng": "78.4667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Telangana", 
    "capital": "admin", 
    "population": "9746000", 
    "population_proper": "6993262",
    "image": "https://thumbs.dreamstime.com/b/charminar-hyderabad-india-hyderabad-india-december-charminar-hyderabad-december-listed-most-recognized-153132366.jpg"
  }, 
  {
    "city": "Pune", 
    "lat": "18.5196", 
    "lng": "73.8553", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "7764000", 
    "population_proper": "3124458",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Pune-City.jpg/640px-Pune-City.jpg"
  }, 
  {
    "city": "Ahmedabad", 
    "lat": "23.0300", 
    "lng": "72.5800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "minor", 
    "population": "7410000", 
    "population_proper": "5570585",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/44/Riverfront_Ahmedabad.jpg"
  }, 
  {
    "city": "Sūrat", 
    "lat": "21.1700", 
    "lng": "72.8300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "5807000", 
    "population_proper": "4466826",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Vesu_%2CSurat.jpg"
  }, 
  {
    "city": "Lucknow", 
    "lat": "26.8470", 
    "lng": "80.9470", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "admin", 
    "population": "3382000", 
    "population_proper": "3382000",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Chhota_imambara_Lucknow.jpg"
  }, 
  {
    "city": "Jaipur", 
    "lat": "26.9167", 
    "lng": "75.8667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "admin", 
    "population": "3073350", 
    "population_proper": "3073350",
    "image": "https://gumlet.assettype.com/knocksense%2Fimport%2F26020419%2Forigin.jpg?auto=format%2Ccompress&fit=max&format=webp&w=480&dpr=2.6"
  }, 
  {
    "city": "Kanpur", 
    "lat": "26.4725", 
    "lng": "80.3311", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "2701324", 
    "population_proper": "2701324",
    "image": "https://gumlet.assettype.com/knocksense%2Fimport%2F29382838%2Forigin.jpg?auto=format%2Ccompress&fit=max&format=webp&w=480&dpr=2.6"
  }, 
  {
    "city": "Mirzāpur", 
    "lat": "25.1500", 
    "lng": "82.5800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "2496970", 
    "population_proper": "2496970",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/11/Mirzapur_3.JPG"
  }, 
  {
    "city": "Nāgpur", 
    "lat": "21.1539", 
    "lng": "79.0831", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "2405665", 
    "population_proper": "2405665",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Aerial_view_of_Nagpur.jpg"
  }, 
  {
    "city": "Ghāziābād", 
    "lat": "28.6667", 
    "lng": "77.4167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "2381452", 
    "population_proper": "2381452",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Indirapuram.jpg"
  }, 
  {
    "city": "Indore", 
    "lat": "22.7206", 
    "lng": "75.8472", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "2201927", 
    "population_proper": "2201927",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSbKF3K75UfYRFrIRqHCzx-1PHafHuZ13XQ9mKqWKpKx0JYb6sVkfxdOv8HInN-BVUiLs&usqp=CAU"
  }, 
  {
    "city": "Vadodara", 
    "lat": "22.3000", 
    "lng": "73.2000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "2065771", 
    "population_proper": "2065771",
    "image": "https://static.toiimg.com/thumb/msid-58522574,imgsize-70328,width-400,resizemode-4/58522574.jpg"
  }, 
  {
    "city": "Vishākhapatnam", 
    "lat": "17.7333", 
    "lng": "83.3167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "2035922", 
    "population_proper": "2035922",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Vizag_aerial_view.jpg?20090314193837"
  }, 
  {
    "city": "Bhopāl", 
    "lat": "23.2500", 
    "lng": "77.4167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "admin", 
    "population": "1883381", 
    "population_proper": "1883381",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Bhopal_lake_view.jpg/640px-Bhopal_lake_view.jpg"
  }, 
 
  {
    "city": "Patna", 
    "lat": "25.6100", 
    "lng": "85.1414", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Bihār", 
    "capital": "admin", 
    "population": "1684222", 
    "population_proper": "1684222",
    "image": "https://images1.livehindustan.com/uploadimage/library/2018/06/21/16_9/16_9_1/PATNA_1529523015_1529523015.JPG"
  }, 
  {
    "city": "Ludhiāna", 
    "lat": "30.9083", 
    "lng": "75.8486", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "1649000", 
    "population_proper": "1545368",
    "image": "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2017/03/19/Pictures/ludhiana-wednesday-january-january-tower-ludhiana-photo_20e14f4e-0c84-11e7-ad00-2dd402d181d7.jpg"
  }, 
  {
    "city": "Āgra", 
    "lat": "27.1800", 
    "lng": "78.0200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "1585705", 
    "population_proper": "1585705",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Taj_Mahal%2C_Agra%2C_India_edit2.jpg/1024px-Taj_Mahal%2C_Agra%2C_India_edit2.jpg"
  }, 
  {
    "city": "Madurai", 
    "lat": "9.9197", 
    "lng": "78.1194", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "minor", 
    "population": "1561129", 
    "population_proper": "1561129",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Madurai%2C_India.jpg"
  }, 
  {
    "city": "Jamshedpur", 
    "lat": "22.8000", 
    "lng": "86.1833", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jharkhand", 
    "capital": "", 
    "population": "1558000", 
    "population_proper": "1558000",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/65/Cityscapes_of_Jamshedpur.jpg"
  }, 
  {
    "city": "Nāsik", 
    "lat": "20.0000", 
    "lng": "73.7833", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "1486053", 
    "population_proper": "1486053",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Nashik_during_1989_Kumbh_Mela.jpg"
  }, 
  {
    "city": "Farīdābād", 
    "lat": "28.4333", 
    "lng": "77.3167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "1394000", 
    "population_proper": "1394000",
    "image": "https://thearchitectsdiary.com/wp-content/uploads/2020/02/Screenshot-2020-02-29-at-12.23.19-PM.png"
  }, 
  {
    "city": "Aurangābād", 
    "lat": "19.8800", 
    "lng": "75.3200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "1371330", 
    "population_proper": "1371330",
    "image": "https://i.ytimg.com/vi/w7CcI5SriKc/hqdefault.jpg"
  }, 
  {
    "city": "Rājkot", 
    "lat": "22.2969", 
    "lng": "70.7984", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "1335397", 
    "population_proper": "1335397",
    "image": "https://1.bp.blogspot.com/-0bUpmStAqyE/YGINTVyVfBI/AAAAAAAAABk/_g66BJOQXDAlVcOpS9agMmARy2oAnpYmACLcBGAsYHQ/s697/Rajkot.jpg"
  }, 
  {
    "city": "Meerut", 
    "lat": "28.9900", 
    "lng": "77.7000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "1305429", 
    "population_proper": "1305429",
    "image": "https://static.toiimg.com/thumb/msid-77663755,width-400,resizemode-4/77663755.jpg"
  }, 
  {
    "city": "Jabalpur", 
    "lat": "23.1667", 
    "lng": "79.9333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "1267564", 
    "population_proper": "1267564",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Marble_Rocks_-_Jabalpur.jpg/1200px-Marble_Rocks_-_Jabalpur.jpg"
  }, 
  {
    "city": "Thāne", 
    "lat": "19.1800", 
    "lng": "72.9633", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "1261517", 
    "population_proper": "1261517",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Mumbai_Bombay_Night.jpg/800px-Mumbai_Bombay_Night.jpg"
  }, 
  {
    "city": "Dhanbād", 
    "lat": "23.7928", 
    "lng": "86.4350", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jharkhand", 
    "capital": "", 
    "population": "1246000", 
    "population_proper": "219636",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Bhatinda_fall.jpg"
  }, 
  {
    "city": "Allahābād", 
    "lat": "25.4550", 
    "lng": "81.8400", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "1201000", 
    "population_proper": "1073438",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Main_Building_of_Allahabad_University_-_Allahabad_-_Uttar_Pradesh_-_India_-_02_%2812566337194%29.jpg/1024px-Main_Building_of_Allahabad_University_-_Allahabad_-_Uttar_Pradesh_-_India_-_02_%2812566337194%29.jpg"
  }, 
  {
    "city": "Vārānasi", 
    "lat": "25.3189", 
    "lng": "83.0128", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "1198491", 
    "population_proper": "1198491",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Manikarnika_Cremation_Ghat%2C_Varanasi.jpg/300px-Manikarnika_Cremation_Ghat%2C_Varanasi.jpg"
  }, 
  {
    "city": "Srīnagar", 
    "lat": "34.0911", 
    "lng": "74.8061", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jammu and Kashmīr", 
    "capital": "admin", 
    "population": "1180570", 
    "population_proper": "1180570",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Srinagar_Garhwal_with_Chauras_view.jpg/1200px-Srinagar_Garhwal_with_Chauras_view.jpg"
  }, 
  {
    "city": "Amritsar", 
    "lat": "31.6167", 
    "lng": "74.8500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "1132383", 
    "population_proper": "1132383",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Golden_Temple_Amritsar.jpeg/1200px-Golden_Temple_Amritsar.jpeg"
  }, 
  {
    "city": "Alīgarh", 
    "lat": "27.8800", 
    "lng": "78.0800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "1131160", 
    "population_proper": "1131160",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/24/AMU_Masjid_-_panoramio.jpg"
  }, 
  {
    "city": "Bhiwandi", 
    "lat": "19.3000", 
    "lng": "73.0667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "1125898", 
    "population_proper": "1125898",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Navi_Mumbai_Municipality_Corporation.jpeg"
  }, 
  {
    "city": "Gwalior", 
    "lat": "26.2150", 
    "lng": "78.1931", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "1101981", 
    "population_proper": "1101981",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Navi_Mumbai_Municipality_Corporation.jpeg"
  }, 
  {
    "city": "Bhilai", 
    "lat": "21.2167", 
    "lng": "81.4333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Chhattīsgarh", 
    "capital": "", 
    "population": "1097000", 
    "population_proper": "1097000",
    "image": "http://s3-ap-southeast-1.amazonaws.com/production-ho-images/public/uploads/editor-images/bhilai/Bhilai-Demographic-wikipedia.jpg"
  }, 
  {
    "city": "Hāora", 
    "lat": "22.5900", 
    "lng": "88.3100", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "1077075", 
    "population_proper": "1077075",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/HOWRAH_BRIDGE_from_howrah_station.jpg"
  }, 
  {
    "city": "Rānchi", 
    "lat": "23.3556", 
    "lng": "85.3347", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jharkhand", 
    "capital": "admin", 
    "population": "1073440", 
    "population_proper": "1073440",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Ranchi_9245.JPG"
  }, 
  {
    "city": "Vijaywada", 
    "lat": "16.5167", 
    "lng": "80.6167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "1048240", 
    "population_proper": "1048240",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Vijayawada_at_Night.jpg/1200px-Vijayawada_at_Night.jpg"
  }, 
  {
    "city": "Chandīgarh", 
    "lat": "30.7353", 
    "lng": "76.7911", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Chandīgarh", 
    "capital": "admin", 
    "population": "1026459", 
    "population_proper": "1026459",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS06NCgwjq94ouaHmiTDCAmSJCgz9vU87xx9w&usqp=CAU"
  }, 
  {
    "city": "Mysore", 
    "lat": "12.3086", 
    "lng": "76.6531", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "1014227", 
    "population_proper": "1014227",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Mysore_Palace%2C_India_%28photo_-_Jim_Ankan_Deka%29.jpg/230px-Mysore_Palace%2C_India_%28photo_-_Jim_Ankan_Deka%29.jpg"
  }, 
  {
    "city": "Raipur", 
    "lat": "21.2379", 
    "lng": "81.6337", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Chhattīsgarh", 
    "capital": "admin", 
    "population": "1010087", 
    "population_proper": "1010087",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/79/Raipur_Skyline_in_2019.png"
  }, 
  {
    "city": "Kota", 
    "lat": "25.1800", 
    "lng": "75.8300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "1001694", 
    "population_proper": "1001694",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Kota_City_of_Rajasthan_View.jpg"
  }, 
  {
    "city": "Bareilly", 
    "lat": "28.3640", 
    "lng": "79.4150", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "1000000", 
    "population_proper": "1000000",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/06/Bareilly_Skyline_02.jpg"
  }, 
  {
    "city": "Jodhpur", 
    "lat": "26.2918", 
    "lng": "73.0168", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "995000", 
    "population_proper": "921476",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/City_Blue_Ramparts2.JPG/400px-City_Blue_Ramparts2.JPG"
  }, 
  {
    "city": "Coimbatore", 
    "lat": "11.0000", 
    "lng": "76.9667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "959823", 
    "population_proper": "959823",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZdzEYrho5qXAUSEw6CT3HPOJuhUGD1AXEIwaTI-jS3CfauEQg9oaXCYW7TFsOSdL2pxM&usqp=CAU"
  }, 
  {
    "city": "Dispur", 
    "lat": "26.1500", 
    "lng": "91.7700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Assam", 
    "capital": "admin", 
    "population": "957352", 
    "population_proper": "957352",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Guwahati_citysky.jpg/800px-Guwahati_citysky.jpg"
  }, 
  {
    "city": "Guwāhāti", 
    "lat": "26.1667", 
    "lng": "91.7667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Assam", 
    "capital": "", 
    "population": "957352", 
    "population_proper": "957352",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/11/Guwahati_citysky.jpg"
  }, 
  {
    "city": "Solāpur", 
    "lat": "17.6833", 
    "lng": "75.9167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "951558", 
    "population_proper": "951558",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQarWbTr3V87vZdnf6LERqb4bZwmszGSvkI5i3wWguckrPN5U9y-RNGVPcowa9q8iVdex0&usqp=CAU"
  }, 
  {
    "city": "Trichinopoly", 
    "lat": "10.8269", 
    "lng": "78.6928", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "916857", 
    "population_proper": "916857",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqCMruXmWmk0Wnnq_1BHbvseq0lnakaRWadxP5L9pQ_JDSdQC1YLTt-puMOrC_0sbEmQE&usqp=CAU"
  }, 
  {
    "city": "Hubli", 
    "lat": "15.3600", 
    "lng": "75.1250", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "890000", 
    "population_proper": "792804",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/93/Panoramic_View_of_Hubli_City_from_Nrupatunga_Hill.jpg"
  }, 
  {
    "city": "Jalandhar", 
    "lat": "31.3256", 
    "lng": "75.5792", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "873725", 
    "population_proper": "873725",
    "image": "https://upload.wikimedia.org/wikipedia/en/f/f5/Jalandhar_Niku_Park_gopal1035.jpg"
  }, 
  {
    "city": "Bhubaneshwar", 
    "lat": "20.2644", 
    "lng": "85.8281", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Odisha", 
    "capital": "admin", 
    "population": "837737", 
    "population_proper": "837737",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Lingaraj_Temple_in_the_evening.jpg"
  }, 
  {
    "city": "Bhayandar", 
    "lat": "19.3000", 
    "lng": "72.8500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "814655", 
    "population_proper": "814655",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpwArVucueXbPhYl4cV8ffqlkTYByl_6Eh0g&usqp=CAU"
  }, 
  {
    "city": "Morādābād", 
    "lat": "28.8418", 
    "lng": "78.7568", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "787000", 
    "population_proper": "721139",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Moradabad_pic_13.JPG/800px-Moradabad_pic_13.JPG"
  }, 
  {
    "city": "Kolhāpur", 
    "lat": "16.7000", 
    "lng": "74.2333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "750000", 
    "population_proper": "561841",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Kolhapur_Mahadwar_BhavaniMandap.JPG/2560px-Kolhapur_Mahadwar_BhavaniMandap.JPG"
  }, 
  {
    "city": "Thiruvananthapuram", 
    "lat": "8.5000", 
    "lng": "76.8997", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Kerala", 
    "capital": "admin", 
    "population": "743691", 
    "population_proper": "743691",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Road_transport_in_Trivandrum.jpg"
  }, 
  {
    "city": "Sahāranpur", 
    "lat": "29.9640", 
    "lng": "77.5460", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "705478", 
    "population_proper": "705478",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM4jhxLOEqtjRTPwDMm8Qp9MD5jlPLW66G4Q&usqp=CAU"
  }, 
  {
    "city": "Warangal", 
    "lat": "17.9756", 
    "lng": "79.6011", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Telangana", 
    "capital": "", 
    "population": "704570", 
    "population_proper": "704570",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-VwdgiUaRf7YjgtyKgSYBGVHnLAz0jKgoei7EhyAm7mbmKDX5VnFhRfk7xuZCjgRgXD0&usqp=CAU"
  }, 
  {
    "city": "Salem", 
    "lat": "11.6500", 
    "lng": "78.1667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "693236", 
    "population_proper": "693236",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Christmas_celebration_walk8-salem_Wiki_DEC2011-Tamil_Nadu.JPG"
  }, 
  {
    "city": "Mālegaon", 
    "lat": "20.5500", 
    "lng": "74.5500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "690844", 
    "population_proper": "435362",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Malegaon_Fort.jpg"
  }, 
  {
    "city": "Kochi", 
    "lat": "9.9667", 
    "lng": "76.2833", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Kerala", 
    "capital": "", 
    "population": "677381", 
    "population_proper": "677381",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Infopark%2C_Kakkanad%2C_Kochi%2C_Kerala%2C_India.jpg"
  }, 
  {
    "city": "Gorakhpur", 
    "lat": "26.7611", 
    "lng": "83.3667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "673446", 
    "population_proper": "673446",
    "image": "https://im.hunt.in/cg/gorakhpur/City-Guide/Gorakhpur.jpg"
  }, 
  {
    "city": "Shimoga", 
    "lat": "13.9304", 
    "lng": "75.5600", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "654055", 
    "population_proper": "319550",
    "image": "http://photos.wikimapia.org/p/00/00/21/86/81_big.jpg"
  }, 
  {
    "city": "Tiruppūr", 
    "lat": "11.1075", 
    "lng": "77.3398", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "650000", 
    "population_proper": "444543",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Covid_19_Tiruppur_Tamil_Nadu_IMG_20200411_125034006.jpg/2560px-Covid_19_Tiruppur_Tamil_Nadu_IMG_20200411_125034006.jpg"
  }, 
  {
    "city": "Guntūr", 
    "lat": "16.3000", 
    "lng": "80.4500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "647508", 
    "population_proper": "647508",
    "image": "https://upload.wikimedia.org/wikipedia/te/a/a0/Guntur_city_center.JPG"
  }, 
  {
    "city": "Raurkela", 
    "lat": "22.2492", 
    "lng": "84.8828", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Odisha", 
    "capital": "", 
    "population": "625831", 
    "population_proper": "483629",
    "image": "https://i.pinimg.com/736x/e1/c7/b3/e1c7b3fced32666270472d2bc115f2e9.jpg"
  }, 
  {
    "city": "Mangalore", 
    "lat": "12.8703", 
    "lng": "74.8806", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "623841", 
    "population_proper": "623841",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Kankanady_skylines_at_Mangalore_CBD_region%2C_Kankanady%2C_Mangalore.jpg"
  }, 
  {
    "city": "Nānded", 
    "lat": "19.1500", 
    "lng": "77.3333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "623708", 
    "population_proper": "550564",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVRaY61KHwqo2nM4ZcUul9sQEls-e_v0Rovw&usqp=CAU"
  }, 
  {
    "city": "Cuttack", 
    "lat": "20.4500", 
    "lng": "85.8667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Odisha", 
    "capital": "", 
    "population": "606007", 
    "population_proper": "606007",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Link_Road%2C_Cuttack.JPG"
  }, 
  {
    "city": "Chānda", 
    "lat": "19.9500", 
    "lng": "79.3000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "595118", 
    "population_proper": "328351",
    "image": "https://images.livemint.com/img/2023/01/03/600x338/Bombay_HC_1672744234046_1672744234202_1672744234202.jpg"
  }, 
  {
    "city": "Dehra Dūn", 
    "lat": "30.3180", 
    "lng": "78.0290", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttarakhand", 
    "capital": "admin", 
    "population": "578420", 
    "population_proper": "578420",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Dehradun_India_2006-2.JPG"
  }, 
  {
    "city": "Durgāpur", 
    "lat": "23.5500", 
    "lng": "87.3200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "566517", 
    "population_proper": "566517",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/View_of_Kalimpong%2C_India.jpg/800px-View_of_Kalimpong%2C_India.jpg"
  }, 
  {
    "city": "Bhāvnagar", 
    "lat": "21.7650", 
    "lng": "72.1369", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "554978", 
    "population_proper": "464602",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e0/View_of_Bhavnagar.jpg"
  }, 
  {
    "city": "Amrāvati", 
    "lat": "20.9333", 
    "lng": "77.7500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "549370", 
    "population_proper": "549370",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Amravati-City-Bus.jpg"
  }, 
  {
    "city": "Nellore", 
    "lat": "14.4333", 
    "lng": "79.9667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "547621", 
    "population_proper": "547621",
    "image": ""
  }, 
  {
    "city": "Ajmer", 
    "lat": "26.4680", 
    "lng": "74.6390", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "542321", 
    "population_proper": "542321",
    "image": "https://www.tripnomadic.com/wp-content/uploads/2021/03/Nellore-1200x675.jpg"
  }, 
  {
    "city": "Bīkaner", 
    "lat": "28.0181", 
    "lng": "73.3169", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "529007", 
    "population_proper": "529007",
    "image": ""
  }, 
  {
    "city": "Agartala", 
    "lat": "23.8333", 
    "lng": "91.2667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tripura", 
    "capital": "admin", 
    "population": "522613", 
    "population_proper": "522613",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Kotgate%2Cbikaner.jpg/2560px-Kotgate%2Cbikaner.jpg"
  }, 
  {
    "city": "Ujjain", 
    "lat": "23.1828", 
    "lng": "75.7772", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "515215", 
    "population_proper": "515215",
    "image": "https://i.pinimg.com/originals/68/62/c5/6862c56928d24d72b1c61f6e91afe127.jpg"
  }, 
  {
    "city": "Jhānsi", 
    "lat": "25.4486", 
    "lng": "78.5696", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "507000", 
    "population_proper": "507000",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/bd/4861576-Jhansi_Jhansi.jpg?20130619174924"
  }, 
  {
    "city": "Ulhāsnagar", 
    "lat": "19.2167", 
    "lng": "73.1500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "506098", 
    "population_proper": "506098",
    "image": "https://static.toiimg.com/thumb/msid-72990739,width-400,resizemode-4/72990739.jpg"
  }, 
  {
    "city": "Jammu", 
    "lat": "32.7333", 
    "lng": "74.8500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jammu and Kashmīr", 
    "capital": "", 
    "population": "502197", 
    "population_proper": "502197",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/72/Jammu_skyline.jpg"
  }, 
  {
    "city": "Jāmnagar", 
    "lat": "22.4700", 
    "lng": "70.0700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "479920", 
    "population_proper": "479920",
    "image": "https://cdn.britannica.com/07/10707-004-6BA3B23D/Royal-Palace-Jamnagar-Gujarat-India.jpg"
  }, 
  {
    "city": "Gaya", 
    "lat": "24.7500", 
    "lng": "85.0167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Bihār", 
    "capital": "", 
    "population": "474093", 
    "population_proper": "474093",
    "image": "https://thumbs.dreamstime.com/b/traffic-jam-gaya-india-jul-holy-city-falgu-river-northeast-state-bihar-158533195.jpg"
  }, 
  {
    "city": "Udaipur", 
    "lat": "24.5833", 
    "lng": "73.6833", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "451100", 
    "population_proper": "451100",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Evening_view%2C_City_Palace%2C_Udaipur.jpg"
  }, 
  {
    "city": "Calicut", 
    "lat": "11.2500", 
    "lng": "75.7667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Kerala", 
    "capital": "minor", 
    "population": "431560", 
    "population_proper": "431560",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/28/Kozhikode_city.jpg"
  }, 
  {
    "city": "Akola", 
    "lat": "20.7333", 
    "lng": "77.0000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "425817", 
    "population_proper": "425817",
    "image": "https://images.indianexpress.com/2020/03/MUM-JJ-FLYOVER202303DL1198.jpg?w=414"
  }, 
  {
    "city": "Bhāgalpur", 
    "lat": "25.2500", 
    "lng": "87.0167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Bihār", 
    "capital": "", 
    "population": "410210", 
    "population_proper": "410210",
    "image": "https://www.jansatta.com/wp-content/uploads/2017/01/bhagalpur-smart-city.jpg"
  }, 
  {
    "city": "Sīkar", 
    "lat": "27.6119", 
    "lng": "75.1397", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "400000", 
    "population_proper": "237579",
    "image": "https://im.hunt.in/cg/Sikar/City-Guide/Laxmangarh_town_of_Sikar.jpg"
  }, 
  {
    "city": "Muzaffarnagar", 
    "lat": "29.4708", 
    "lng": "77.7033", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "392451", 
    "population_proper": "392451",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW2A97svOPBRom0FtnIr6HbtH6ek8_kEP-JqJN_YqUw4eQmCutP8FGfsbmJFWMDAkIsY8&usqp=CAU"
  }, 
  {
    "city": "Bhīlwāra", 
    "lat": "25.3500", 
    "lng": "74.6333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "389911", 
    "population_proper": "326431",
    "image": "https://urban.rajasthan.gov.in/content/dam/raj/udh/ulbs/ajmer%20division/bhilwara/images/DSC_0247.JPG"
  }, 
  {
    "city": "Rohtak", 
    "lat": "28.9000", 
    "lng": "76.5667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "374292", 
    "population_proper": "374292",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Quilla_road_rohtak.jpg/1200px-Quilla_road_rohtak.jpg"
  }, 
  {
    "city": "Ahmadnagar", 
    "lat": "19.0833", 
    "lng": "74.7333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "350859", 
    "population_proper": "350859",
    "image": "https://c8.alamy.com/comp/F76296/fort-ahmednagar-maharashtra-india-asia-F76296.jpg"
  }, 
  {
    "city": "Alwar", 
    "lat": "27.5667", 
    "lng": "76.6167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "341422", 
    "population_proper": "341422",
    "image": "https://media.gettyimages.com/id/509106797/photo/india-rajasthan-alwar-elevated-view-of-hope-circus.jpg?s=612x612&w=gi&k=20&c=EB0oFTdmDkQVlcy7ECKdhvl--lP4MniIsiX1EYEcDuQ="
  }, 
  {
    "city": "Bilāspur", 
    "lat": "22.1500", 
    "lng": "82.0167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Chhattīsgarh", 
    "capital": "", 
    "population": "331030", 
    "population_proper": "331030",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Bilaspur_Junction_Railway_Station_Building_001.jpg/640px-Bilaspur_Junction_Railway_Station_Building_001.jpg"
  }, 
  {
    "city": "Mathura", 
    "lat": "27.4833", 
    "lng": "77.6833", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "330511", 
    "population_proper": "330511",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Vishram_Ghat.jpg/1200px-Vishram_Ghat.jpg"
  }, 
  {
    "city": "Patiāla", 
    "lat": "30.3204", 
    "lng": "76.3850", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "329224", 
    "population_proper": "329224",
    "image": "https://images.hindustantimes.com/rf/image_size_960x540/HT/p2/2018/06/30/Pictures/patiala-hindustan-mubarak-patiala-photo-bharat-bhushan_c859263e-7c31-11e8-8d5f-3f0c905295d2.jpg"
  }, 
  {
    "city": "Trichūr", 
    "lat": "10.5200", 
    "lng": "76.2100", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Kerala", 
    "capital": "", 
    "population": "315596", 
    "population_proper": "315596",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/JJP_112.jpg/1200px-JJP_112.jpg"
  }, 
  {
    "city": "Kulti", 
    "lat": "23.7300", 
    "lng": "86.8500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "313809", 
    "population_proper": "313809",
    "image": "https://im.hunt.in/cg/wb/Kulti/City-Guide/kul.jpg"
  }, 
  {
    "city": "Sambalpur", 
    "lat": "21.4704", 
    "lng": "83.9701", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Odisha", 
    "capital": "", 
    "population": "310852", 
    "population_proper": "162887",
    "image": "https://assets.telegraphindia.com/telegraph/30orisam.jpg"
  }, 

  {
    "city": "Hisar", 
    "lat": "29.1489", 
    "lng": "75.7367", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "307024", 
    "population_proper": "307024",
    "image": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2022/1/Desk/2022_1$largeimg_135644908.jpg"
  }, 
  {
    "city": "Fīrozābād", 
    "lat": "27.1500", 
    "lng": "78.3949", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "306409", 
    "population_proper": "306409",
    "image": "https://im.hunt.in/cg/firozabad/City-Guide/A-View-of-Firozabad.jpg"
  }, 

  {
    "city": "Rāmpur", 
    "lat": "28.8154", 
    "lng": "79.0250", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "296418", 
    "population_proper": "296418",
    "image": "https://thumbs.dreamstime.com/b/rampur-bushahr-town-himachal-pradesh-india-shimla-district-state-186513912.jpg"
  }, 
  {
    "city": "Bāli", 
    "lat": "22.6500", 
    "lng": "88.3400", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "293373", 
    "population_proper": "293373",
    "image": "https://www.tripsavvy.com/thmb/gekD7K-R8wbTI0bqVaqlXVxiqVY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/02_jalanlegian_bali-588479955f9b58bdb393e5dc.jpg"
  }, 
  {
    "city": "Pānīpat", 
    "lat": "29.4004", 
    "lng": "76.9700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "292808", 
    "population_proper": "292808",
    "image": "https://cdn.britannica.com/17/9717-050-216E6555/wheat-market-Panipat-Haryana-India.jpg"
  }, 
  {
    "city": "Bhuj", 
    "lat": "23.2504", 
    "lng": "69.8100", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "289429", 
    "population_proper": "289429",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Chhatedi_of_Bhuj.jpg/321px-Chhatedi_of_Bhuj.jpg"
  }, 
  {
    "city": "Tirupati", 
    "lat": "13.6500", 
    "lng": "79.4200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "287482", 
    "population_proper": "287482",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/01/Tirupati_city_view_from_Tirumala_hills_01.jpg"
  }, 
  {
    "city": "Āīzawl", 
    "lat": "23.7104", 
    "lng": "92.7200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mizoram", 
    "capital": "admin", 
    "population": "283021", 
    "population_proper": "265331",
    "image": ""
  }, 
  {
    "city": "Bārāsat", 
    "lat": "22.2333", 
    "lng": "88.4500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "278435", 
    "population_proper": "278435",
    "image": "https://www.goodridestories.com/wp-content/uploads/2020/06/P1160945-1024x576.jpg"
  }, 
  {
    "city": "Ratlām", 
    "lat": "23.3167", 
    "lng": "75.0667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "273892", 
    "population_proper": "273892",
    "image": "https://blog.delhifoodwalks.com/wp-content/uploads/2019/09/IMG-20190830-WA0006.jpg"
  }, 
  {
    "city": "Imphāl", 
    "lat": "24.8200", 
    "lng": "93.9500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Manipur", 
    "capital": "admin", 
    "population": "268243", 
    "population_proper": "268243",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/91/Imphal_city.jpg"
  }, 
  {
    "city": "Anantapur", 
    "lat": "14.6833", 
    "lng": "77.6000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "267161", 
    "population_proper": "267161",
    "image": "https://etimg.etb2bimg.com/photo/78767536.cms"
  }, 
  {
    "city": "Rāichūr", 
    "lat": "16.2104", 
    "lng": "77.3550", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "255240", 
    "population_proper": "225962",
    "image": "https://www.earthtrip.in/gallery/cityImage/1460112677_Raichur.jpg"
  }, 
  {
    "city": "Bharatpur", 
    "lat": "27.2172", 
    "lng": "77.4900", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "252342", 
    "population_proper": "252342",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/af/Bharatpur_museums.jpg"
  }, 
  {
    "city": "Begusarai", 
    "lat": "25.4200", 
    "lng": "86.1300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Bihār", 
    "capital": "", 
    "population": "252008", 
    "population_proper": "252008",
    "image": "https://www.travelguideinc.com/wp-content/uploads/2017/10/main-image-Begusarai.jpg"
  }, 
  {
    "city": "Sonīpat", 
    "lat": "28.9958", 
    "lng": "77.0114", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "250521", 
    "population_proper": "250521",
    "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/b9/76/c6/outside-mall.jpg?w=600&h=400&s=1"
  }, 
  {
    "city": "Porbandar", 
    "lat": "21.6425", 
    "lng": "69.6047", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "234684", 
    "population_proper": "138872",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Porbandar_skyline.JPG/2560px-Porbandar_skyline.JPG"
  }, 
  {
    "city": "Puducherry", 
    "lat": "11.9300", 
    "lng": "79.8300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Puducherry", 
    "capital": "admin", 
    "population": "227411", 
    "population_proper": "227411",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Rock_beach_aerial_view.jpg/800px-Rock_beach_aerial_view.jpg"
  }, 
  {
    "city": "Sambhal", 
    "lat": "28.5800", 
    "lng": "78.5500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "220813", 
    "population_proper": "220813",
    "image": "https://im.hunt.in/cg/Sambhal/City-Guide/manokamna.jpg"
  }, 
  {
    "city": "Naihāti", 
    "lat": "22.9000", 
    "lng": "88.4200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "217900", 
    "population_proper": "217900",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Naihati_RBC_Road_by_Piyal_Kundu.JPG/1200px-Naihati_RBC_Road_by_Piyal_Kundu.JPG"
  }, 
  {
    "city": "Kharagpur", 
    "lat": "22.3302", 
    "lng": "87.3237", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "207604", 
    "population_proper": "207604",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/1c/a7/b4/51/caption.jpg"
  }, 

  {
    "city": "Shimla", 
    "lat": "31.1033", 
    "lng": "77.1722", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Himāchal Pradesh", 
    "capital": "admin", 
    "population": "206575", 
    "population_proper": "206575",
    "image": "https://thumbs.dreamstime.com/b/shimla-india-shimla-aerial-view-capital-city-indian-state-himachal-pradesh-located-northern-india-114069361.jpg"
  }, 
  {
    "city": "Puri", 
    "lat": "19.8000", 
    "lng": "85.8167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Odisha", 
    "capital": "", 
    "population": "201026", 
    "population_proper": "201026",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/09/ee/11/39/new-marine-drive-puri.jpg"
  }, 
  {
    "city": "Haldia", 
    "lat": "22.0257", 
    "lng": "88.0583", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "200762", 
    "population_proper": "200762",
    "image": "https://www.salientdesignstudio.com/admin/uploads/53_p_7386.jpg"
  }, 
  {
    "city": "Nandyāl", 
    "lat": "15.4800", 
    "lng": "78.4800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "200516", 
    "population_proper": "200516",
    "image": "https://im.hunt.in/cg//Nandyal/City-Guide/nandyal3.jpg"
  }, 
  {
    "city": "Bhiwāni", 
    "lat": "28.7833", 
    "lng": "76.1333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "197662", 
    "population_proper": "197662",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/11/49/cb/c4/it-is-one-of-the-places.jpg"
  }, 
  {
    "city": "Gurgaon", 
    "lat": "28.4500", 
    "lng": "77.0200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "197340", 
    "population_proper": "197340",
    "image": "https://images.hindustantimes.com/rf/image_size_960x540/HT/p2/2018/06/01/Pictures/aerial-view-photo-gurugram-using-ht-drone_29ee0454-657c-11e8-b4a9-2154dcd09999.jpg"
  }, 
  {
    "city": "Burhānpur", 
    "lat": "21.3004", 
    "lng": "76.1300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "197233", 
    "population_proper": "197233",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Burhanpur_town_streets_-_panoramio.jpg/640px-Burhanpur_town_streets_-_panoramio.jpg"
  }, 
  {
    "city": "Ghāndīnagar", 
    "lat": "23.2200", 
    "lng": "72.6800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "admin", 
    "population": "195891", 
    "population_proper": "195891",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/77/Akshardham_Gandhinagar_Gujarat.jpg"
  }, 
  {
    "city": "Baharampur", 
    "lat": "24.1000", 
    "lng": "88.2500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "195223", 
    "population_proper": "195223",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Aerial_View_of_Berhampore_and_Ganges.jpg/1280px-Aerial_View_of_Berhampore_and_Ganges.jpg"
  }, 
  {
    "city": "Rāiganj", 
    "lat": "25.6167", 
    "lng": "88.1167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "183612", 
    "population_proper": "183612",
    "image": "https://im.hunt.in/cg/Raiganj/City-Guide/raiganj2.jpg"
  }, 
  {
    "city": "Bhusāval", 
    "lat": "21.0200", 
    "lng": "75.8300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "183001", 
    "population_proper": "172366",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Tapti_river_%285%29.jpg/1200px-Tapti_river_%285%29.jpg"
  }, 
  {
    "city": "Shrīrāmpur", 
    "lat": "22.7500", 
    "lng": "88.3400", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "181842", 
    "population_proper": "181842",
    "image": "https://thumbs.dreamstime.com/b/facade-humayun-s-tomb-against-blue-sky-delhi-india-bhusawal-maharashtra-india-feb-facade-humayun-s-tomb-against-216966886.jpg"
  }, 
  {
    "city": "Sirsa", 
    "lat": "29.4904", 
    "lng": "75.0300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "181639", 
    "population_proper": "160129",
    "image": "https://images.indianexpress.com/2020/02/Sirsa.jpg"
  }, 
  {
    "city": "Jaunpur", 
    "lat": "25.7333", 
    "lng": "82.6833", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "180362", 
    "population_proper": "180362",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Shahi_bridge%2C_Jaunpur.jpg"
  }, 
  {
    "city": "Hugli", 
    "lat": "22.9000", 
    "lng": "88.3900", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "179931", 
    "population_proper": "179931",
    "image": "https://thumbs.dreamstime.com/b/india-city-ganga-river-kolkata-india-cityhugli-river-hugli-river-hugli-also-spelled-hooghly-river-west-bengal-state-173056128.jpg"
  }, 
  {
    "city": "Vellore", 
    "lat": "12.9204", 
    "lng": "79.1500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "177081", 
    "population_proper": "177081",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/22/Vellore_City_Hill_backdrop.JPG"
  }, 
  {
    "city": "Chīrāla", 
    "lat": "15.8200", 
    "lng": "80.3500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "172826", 
    "population_proper": "172826",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRU3JXdt3dfbMzirsm7RyGrdatcCNRUK3z3c-fgjvlJQQY6CEPuE528j9bTZ48wGuaLbo&usqp=CAU"
  }, 
  {
    "city": "Machilīpatnam", 
    "lat": "16.1667", 
    "lng": "81.1333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "169892", 
    "population_proper": "169892",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/70/Machilipatnam_koneru_center_3.JPG"
  }, 
  {
    "city": "Fatehpur", 
    "lat": "25.8804", 
    "lng": "80.8000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "166480", 
    "population_proper": "166480",
    "image": "https://i0.wp.com/somanytraveltales.com/wp-content/uploads/2021/12/Anup-Talao-2-Fatehpur-1-scaled.jpg?fit=1024%2C697&ssl=1"
  }, 
  {
    "city": "Udipi", 
    "lat": "13.3322", 
    "lng": "74.7461", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "165401", 
    "population_proper": "165401",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/da/Udupi_Krishna_Temple.jpg"
  }, 
  {
    "city": "Tenāli", 
    "lat": "16.2430", 
    "lng": "80.6400", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "164937", 
    "population_proper": "164937",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThoiSKzytJVpWNxJ6_PBuPLPmtTxtLZV-mNcy9xPl5msRV3CCK9HhiW6FMrRX8mhpcwNg&usqp=CAU"
  }, 
  {
    "city": "Godhra", 
    "lat": "22.7755", 
    "lng": "73.6149", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "161925", 
    "population_proper": "161925",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/1d/37/d9/57/godhra-trimandir.jpg"
  }, 
  {
    "city": "Chittoor", 
    "lat": "13.2000", 
    "lng": "79.1167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "160722", 
    "population_proper": "160722",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Cto_railway_station.jpg"
  }, 
  {
    "city": "Harīpur", 
    "lat": "31.5200", 
    "lng": "75.9800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "158142", 
    "population_proper": "158142",
    "image": ""
  }, 
  {
    "city": "Vidisha", 
    "lat": "23.5239", 
    "lng": "77.8061", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "155959", 
    "population_proper": "155959",
    "image": ""
  }, 
  {
    "city": "Pathānkot", 
    "lat": "32.2689", 
    "lng": "75.6497", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "155909", 
    "population_proper": "155909",
    "image": ""
  }, 
  {
    "city": "Krishnanagar", 
    "lat": "23.4000", 
    "lng": "88.5000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "153062", 
    "population_proper": "153062",
    "image": ""
  }, 
  {
    "city": "Silchar", 
    "lat": "24.7904", 
    "lng": "92.7900", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Assam", 
    "capital": "", 
    "population": "152393", 
    "population_proper": "152393",
    "image": "https://cdn.techjuice.pk/wp-content/uploads/2018/11/pakistan-digital-city.jpg"
  }, 
  {
    "city": "Shāntipur", 
    "lat": "23.2500", 
    "lng": "88.4300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "151777", 
    "population_proper": "151777",
    "image": "https://im.hunt.in/cg/santipur/City-Guide/shay.jpg"
  }, 
  {
    "city": "Hindupur", 
    "lat": "13.8300", 
    "lng": "77.4900", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "151677", 
    "population_proper": "151677",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/32/Nandi_Lepakshi_Temple_Hindupur_10.jpg"
  }, 
  {
    "city": "Jāmuria", 
    "lat": "23.7000", 
    "lng": "87.0800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "149220", 
    "population_proper": "149220",
    "image": "https://i.10xmt.com/unsafe/768x0/smart/images/media/Billboard-Jamuria-Asansol-8399.jpg"
  }, 

  {
    "city": "Ambāla", 
    "lat": "30.3786", 
    "lng": "76.7725", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Haryāna", 
    "capital": "", 
    "population": "146787", 
    "population_proper": "146787",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/70/Ambala_Cantt_station.jpg"
  }, 
  {
    "city": "Mauli", 
    "lat": "30.7194", 
    "lng": "76.7181", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Punjab", 
    "capital": "", 
    "population": "146213", 
    "population_proper": "146213",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Shri_Devi_Mauli_Mandir_at_Tiroda_in_Distt._Sindhudurg_-_panoramio.jpg/320px-Shri_Devi_Mauli_Mandir_at_Tiroda_in_Distt._Sindhudurg_-_panoramio.jpg"
  }, 

  {
    "city": "Shillong", 
    "lat": "25.5744", 
    "lng": "91.8789", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Meghālaya", 
    "capital": "admin", 
    "population": "143229", 
    "population_proper": "143229",
    "image": "https://assets.telegraphindia.com/telegraph/c5beb575-d255-43e5-b8f4-60dae4ebc74d.jpg"
  }, 
  {
    "city": "New Delhi", 
    "lat": "28.7000", 
    "lng": "77.2000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Delhi", 
    "capital": "primary", 
    "population": "142004", 
    "population_proper": "142004",
    "image": "https://m.economictimes.com/thumb/msid-77587330,width-1200,height-900,resizemode-4,imgsize-591770/18.jpg"
  }, 
  {
    "city": "Mandsaur", 
    "lat": "24.0300", 
    "lng": "75.0800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "141667", 
    "population_proper": "141667",
    "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/3c/3a/e1/pashupatinath-temple.jpg?w=500&h=300&s=1"
  }, 
  {
    "city": "Tiruvannāmalai", 
    "lat": "12.2604", 
    "lng": "79.1000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "138243", 
    "population_proper": "138243",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Thiruvannamalai%2C_Arunachalesvara_Temple%2C_City%2C_India.jpg/1200px-Thiruvannamalai%2C_Arunachalesvara_Temple%2C_City%2C_India.jpg"
  }, 
  {
    "city": "Hassan", 
    "lat": "13.0050", 
    "lng": "76.1028", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Karnātaka", 
    "capital": "", 
    "population": "133436", 
    "population_proper": "133436",
    "image": "https://live.staticflickr.com/4053/4285426285_52e15fe95a_b.jpg"
  }, 
  {
    "city": "Port Blair", 
    "lat": "11.6667", 
    "lng": "92.7500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andaman and Nicobar Islands", 
    "capital": "admin", 
    "population": "127562", 
    "population_proper": "112050",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/2b/PortBlair_SeasideRoad.JPG"
  }, 
  {
    "city": "Alīpur Duār", 
    "lat": "26.4837", 
    "lng": "89.5667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "127342", 
    "population_proper": "127342",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Alipurduar_Railway_Junction_Station.jpg/800px-Alipurduar_Railway_Junction_Station.jpg"
  }, 
  {
    "city": "Hāthras", 
    "lat": "27.6000", 
    "lng": "78.0500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "126882", 
    "population_proper": "126882",
    "image": "https://st2.indiarailinfo.com/kjfdsuiemjvcya6/0/6/5/8/2366658/0/img201707302013323115589.jpg"
  }, 


  {
    "city": "Rishra", 
    "lat": "22.7100", 
    "lng": "88.3500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "124577", 
    "population_proper": "124577",
    "image": ""
  }, 
  {
    "city": "Dharmavaram", 
    "lat": "14.4142", 
    "lng": "77.7150", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "121874", 
    "population_proper": "121874",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/63/Rishra_Sky_Line.jpg"
  }, 
  {
    "city": "Darjeeling", 
    "lat": "27.0417", 
    "lng": "88.2631", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "118805", 
    "population_proper": "118805",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/Darjeeling_City_View.jpg"
  }, 
  {
    "city": "Sopur", 
    "lat": "34.3000", 
    "lng": "74.4700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jammu and Kashmīr", 
    "capital": "", 
    "population": "118608", 
    "population_proper": "118608",
    "image": "https://c8.alamy.com/comp/2HM19DP/art-inspired-by-view-of-sopore-near-the-bridge-over-the-jhelum-sopur-original-title-the-houses-behind-the-bridge-are-of-sopore-near-baramulla-in-jammu-and-kashmir-the-bridge-a-landmark-of-sopore-spans-the-jhelum-river-samuel-bourne-signed-by-artist-jammu-en-kasjmir-1864-classic-works-modernized-by-artotop-with-a-splash-of-modernity-shapes-color-and-value-eye-catching-visual-impact-on-art-emotions-through-freedom-of-artworks-in-a-contemporary-way-a-timeless-message-pursuing-a-wildly-creative-new-direction-artists-turning-to-the-digital-medium-and-creating-the-artotop-nft-2HM19DP.jpg"
  }, 
  {
    "city": "Adilābād", 
    "lat": "19.6667", 
    "lng": "78.5333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Telangana", 
    "capital": "", 
    "population": "117167", 
    "population_proper": "117167",
    "image": "https://thumbs.dreamstime.com/b/adilabad-fort-india-delhi-tourism-164996185.jpg"
  }, 
  {
    "city": "Titāgarh", 
    "lat": "22.7400", 
    "lng": "88.3700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "116541", 
    "population_proper": "116541",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Barrackpore_Trunk_Road_-_Titagarh_-_North_24_Parganas_2012-04-11_9500.JPG"
  }, 
  {
    "city": "Chittaurgarh", 
    "lat": "24.8894", 
    "lng": "74.6239", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "116406", 
    "population_proper": "116406",
    "image": "https://thumbs.dreamstime.com/b/aerial-view-chittorgarh-fort-rajasthan-india-aerial-view-chittorgarh-town-fort-rajasthan-state-india-113041750.jpg"
  }, 
  {
    "city": "Bangaon", 
    "lat": "23.0700", 
    "lng": "88.8200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "108864", 
    "population_proper": "108864",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/19/BONGAON_BRIDGE_NEW_-_panoramio.jpg"
  }, 
  {
    "city": "Kalyani", 
    "lat": "22.9750", 
    "lng": "88.4344", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "100575", 
    "population_proper": "100575",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Kalyani_railway_station_main_and_branch%2C_Kalyani_Nadia%2C_West_Bengal_01.jpg"
  }, 
  {
    "city": "Gangtok", 
    "lat": "27.3300", 
    "lng": "88.6200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Sikkim", 
    "capital": "admin", 
    "population": "100286", 
    "population_proper": "100286",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/View_of_Gangtok_City_from_Crown_Prince_Tenzing_Kunzang_Namgyal_Walkway.jpg/1280px-View_of_Gangtok_City_from_Crown_Prince_Tenzing_Kunzang_Namgyal_Walkway.jpg"
  }, 
  {
    "city": "Kohīma", 
    "lat": "25.6667", 
    "lng": "94.1194", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Nāgāland", 
    "capital": "admin", 
    "population": "99039", 
    "population_proper": "99039",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/01/Kohima_City.jpeg"
  }, 

  {
    "city": "Aurangābād", 
    "lat": "24.7704", 
    "lng": "84.3800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Bihār", 
    "capital": "", 
    "population": "95929", 
    "population_proper": "95929",
    "image": "https://img.traveltriangle.com/blog/wp-content/uploads/2020/01/Cover-for-Places-To-Visit-In-Aurangabad_16th-jan.jpg"
  }, 
  {
    "city": "Kāvali", 
    "lat": "14.9123", 
    "lng": "79.9944", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "90099", 
    "population_proper": "90099",
    "image":"https://upload.wikimedia.org/wikipedia/commons/8/86/Kavali_aerial_view.jpg"
  }, 
  {
    "city": "Anakāpalle", 
    "lat": "17.6800", 
    "lng": "83.0200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "86519", 
    "population_proper": "86519",
    "image": "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1d/15/66/e1/gardenview.jpg"
  }, 
  {
    "city": "Sirsilla", 
    "lat": "18.3800", 
    "lng": "78.8300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Telangana", 
    "capital": "", 
    "population": "83186", 
    "population_proper": "83186",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPygcUuYp0q4j0ZoRT1k7gRL6mz8J-uAnn95649YGDoU0hUKZEVwUTuso_fpfkdZOZpKc&usqp=CAU"
  }, 
  {
    "city": "Kottagūdem", 
    "lat": "17.5500", 
    "lng": "80.6300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Telangana", 
    "capital": "", 
    "population": "79819", 
    "population_proper": "79819",
    "image": "https://static.readytotrip.com/upload/information_system_24/1/5/0/item_1509418/photo_19937870.jpg"
  }, 
  {
    "city": "Tanuku", 
    "lat": "16.7500", 
    "lng": "81.7000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "77962", 
    "population_proper": "77962",
    "image": "https://media-cdn.tripadvisor.com/media/photo-s/11/2b/de/7c/very-good-ambience-9100231555.jpg"
  }, 
  {
    "city": "Bodhan", 
    "lat": "18.6700", 
    "lng": "77.9000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Telangana", 
    "capital": "", 
    "population": "77573", 
    "population_proper": "77573",
    "image": "https://teja13.kuikr.com/is/p/t20/1280x800/public/images/gallery/locality_masthead/37322/Nizamabad_Bodhan_Masthead_5614d26de39d2.jpg"
  }, 
  {
    "city": "Bāpatla", 
    "lat": "15.8889", 
    "lng": "80.4700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "70777", 
    "population_proper": "70777",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Batala_Dera_Sahib.jpg"
  }, 
  {
    "city": "Badvel", 
    "lat": "14.7500", 
    "lng": "79.0500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "70626", 
    "population_proper": "70626",
    "image": "https://images.newindianexpress.com/uploads/user/imagelibrary/2021/10/23/w900X450/Development.jpg?w=400&dpr=2.6"
  }, 

  {
    "city": "Jaisalmer", 
    "lat": "26.9167", 
    "lng": "70.9167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "65471", 
    "population_proper": "65471",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/View_from_Jaisalmer_fort.jpg/1200px-View_from_Jaisalmer_fort.jpg"
  }, 
  {
    "city": "Nagari", 
    "lat": "13.3300", 
    "lng": "79.5800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "62253", 
    "population_proper": "62253",
    "image": ""
  }, 
  {
    "city": "Vinukonda", 
    "lat": "16.0500", 
    "lng": "79.7500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "59725", 
    "population_proper": "59725",
    "image": ""
  }, 
  {
    "city": "Itānagar", 
    "lat": "27.1000", 
    "lng": "93.6200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Arunāchal Pradesh", 
    "capital": "admin", 
    "population": "59490", 
    "population_proper": "59490",
    "image": ""
  }, 
  {
    "city": "Tezpur", 
    "lat": "26.6338", 
    "lng": "92.8000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Assam", 
    "capital": "", 
    "population": "58851", 
    "population_proper": "58851",
    "image": ""
  }, 
  {
    "city": "Vrindāvan", 
    "lat": "27.5806", 
    "lng": "77.7006", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "56618", 
    "population_proper": "56618",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Bhaktivedanta_Swami_Marg_-_Vrindaban_2013-02-24_6736.JPG/1200px-Bhaktivedanta_Swami_Marg_-_Vrindaban_2013-02-24_6736.JPG"
  }, 
  {
    "city": "Mandapeta", 
    "lat": "16.8700", 
    "lng": "81.9300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "56063", 
    "population_proper": "56063",
    "image": ""
  }, 

  {
    "city": "Pithāpuram", 
    "lat": "17.1167", 
    "lng": "82.2667", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "54859", 
    "population_proper": "54859",
    "image": ""
  },  
  {
    "city": "Puttūr", 
    "lat": "13.4500", 
    "lng": "79.5500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "54092", 
    "population_proper": "54092",
    "image": ""
  }, 
  {
    "city": "Jalor", 
    "lat": "25.3500", 
    "lng": "72.6167", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "54081", 
    "population_proper": "54081",
    "image": ""
  }, 

  {
    "city": "Dholka", 
    "lat": "22.7200", 
    "lng": "72.4700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "53792", 
    "population_proper": "53792",
    "image": ""
  }, 
  {
    "city": "Sihor", 
    "lat": "21.7000", 
    "lng": "71.9700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "52603", 
    "population_proper": "52603",
    "image": ""
  }, 
  {
    "city": "Rāmeswaram", 
    "lat": "9.2800", 
    "lng": "79.3000", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Tamil Nādu", 
    "capital": "", 
    "population": "44856", 
    "population_proper": "44856",
    "image": ""
  }, 
  {
    "city": "Rājgīr", 
    "lat": "25.0300", 
    "lng": "85.4200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Bihār", 
    "capital": "", 
    "population": "41587", 
    "population_proper": "41587",
    "image": ""
  }, 
  {
    "city": "Naini Tal", 
    "lat": "29.3919", 
    "lng": "79.4542", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttarakhand", 
    "capital": "", 
    "population": "41377", 
    "population_proper": "41377",
    "image": ""
  }, 
  {
    "city": "Maihar", 
    "lat": "24.2700", 
    "lng": "80.7500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "40192", 
    "population_proper": "40192",
    "image": ""
  }, 
  {
    "city": "Panji", 
    "lat": "15.4800", 
    "lng": "73.8300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Goa", 
    "capital": "admin", 
    "population": "40017", 
    "population_proper": "40017",
    "image": ""
  }, 
  {
    "city": "Junnar", 
    "lat": "19.2000", 
    "lng": "73.8800", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Mahārāshtra", 
    "capital": "", 
    "population": "40000", 
    "population_proper": "40000",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Junnar_city.jpg/640px-Junnar_city.jpg"
  }, 
  {
    "city": "Damān", 
    "lat": "20.4170", 
    "lng": "72.8500", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "admin", 
    "population": "39737", 
    "population_proper": "39737",
    "image": ""
  }, 

  {
    "city": "Solan", 
    "lat": "30.9200", 
    "lng": "77.1200", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Himāchal Pradesh", 
    "capital": "", 
    "population": "39256", 
    "population_proper": "39256",
    "image": ""
  }, 
  {
    "city": "Dwārka", 
    "lat": "22.2403", 
    "lng": "68.9686", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Gujarāt", 
    "capital": "", 
    "population": "38873", 
    "population_proper": "38873",
    "image": ""
  }, 
  {
    "city": "Pathanāmthitta", 
    "lat": "9.2647", 
    "lng": "76.7872", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Kerala", 
    "capital": "", 
    "population": "37802", 
    "population_proper": "37802",
    "image": ""
  }, 

  {
    "city": "Udhampur", 
    "lat": "32.9300", 
    "lng": "75.1300", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Jammu and Kashmīr", 
    "capital": "", 
    "population": "35507", 
    "population_proper": "35507",
    "image": ""
  }, 
  {
    "city": "Umaria", 
    "lat": "23.5245", 
    "lng": "80.8365", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "33114", 
    "population_proper": "33114",
    "image": ""
  }, 
  {
    "city": "Fatehpur Sīkri", 
    "lat": "27.0911", 
    "lng": "77.6611", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Uttar Pradesh", 
    "capital": "", 
    "population": "32905", 
    "population_proper": "32905",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Fatehpur_Sikri_042.JPG/800px-Fatehpur_Sikri_042.JPG"
  }, 
  {
    "city": "Narasannapeta", 
    "lat": "18.4151", 
    "lng": "84.0447", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Andhra Pradesh", 
    "capital": "", 
    "population": "26280", 
    "population_proper": "26280",
    "image": ""
  }, 
  {
    "city": "Jaynagar-Majilpur", 
    "lat": "22.1772", 
    "lng": "88.4258", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "West Bengal", 
    "capital": "", 
    "population": "25922", 
    "population_proper": "25922",
    "image": ""
  }, 
  {
    "city": "Khajurāho", 
    "lat": "24.8500", 
    "lng": "79.9333", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Madhya Pradesh", 
    "capital": "", 
    "population": "24481", 
    "population_proper": "24481",
    "image": ""
  }, 
  {
    "city": "Diu", 
    "lat": "20.7197", 
    "lng": "70.9904", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Damān and Diu", 
    "capital": "", 
    "population": "23779", 
    "population_proper": "23779",
    "image": "https://www.smartcitiescouncil.com/sites/default/files/article/Diu.jpg"
  }, 
  {
    "city": "Gauripur", 
    "lat": "26.0800", 
    "lng": "89.9700", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Assam", 
    "capital": "", 
    "population": "23477", 
    "population_proper": "23477",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Chourange_More%2C_Station_Road%2C_Gouripur%2C_Dhubri.JPG/440px-Chourange_More%2C_Station_Road%2C_Gouripur%2C_Dhubri.JPG"
  }, 
  {
    "city": "Abu", 
    "lat": "24.5925", 
    "lng": "72.7083", 
    "country": "India", 
    "iso2": "IN", 
    "admin_name": "Rājasthān", 
    "capital": "", 
    "population": "22943", 
    "population_proper": "22943",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Mount_Abu.jpg"
  }
]
}


export default India;