// ./src/app/layout.js

'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';
import Footer from '../components/footer/Footer';
import Navbar from '@/components/navbar/Navbar';
import NavbarSingle from '@/components/single-website/NavbarSingle';
import FooterSingle from '@/components/single-website/FooterSingle';

const inter = Inter({ subsets: ['latin'], weight: ['300','400','500','700','900'] });


const metadata = {
  title: 'Deal acres',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isSingleWebsitePage = pathname === '/single-website';

  return (
    <html lang="en">
      <body className={inter.className}>
        {isSingleWebsitePage ? <NavbarSingle /> : <Navbar />}
        {children}
        {isSingleWebsitePage ? <FooterSingle /> : <Footer />} 
      </body>
    </html>
  );
}


export { metadata };
