export const hariyana =[
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Ambala", link: "#" },
    { name: "Real Estate Agent in Jhajjar", link: "#" },
    { name: "Real Estate Agent in Panipat", link: "#" },
    { name: "Real Estate Agent in Sonepat", link: "#" },
    { name: "Real Estate Agent in Rewari", link: "#" },
    { name: "Real Estate Agent in Jind", link: "#" },
    { name: "Real Estate Agent in Kaithal", link: "#" },
    { name: "Real Estate Agent in Sirsa", link: "#" },
    { name: "Real Estate Agent in Faridabad", link: "#" },
    { name: "Real Estate Agent in Gurgaon", link: "#" },
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Kurukshetra", link: "#" },
    { name: "Real Estate Agent in Yamunanagar", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },

  ]


  export const gurugaon =[
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Ambala", link: "#" },
    { name: "Real Estate Agent in Jhajjar", link: "#" },
    { name: "Real Estate Agent in Panipat", link: "#" },
    { name: "Real Estate Agent in Sonepat", link: "#" },
    { name: "Real Estate Agent in Rewari", link: "#" },
    { name: "Real Estate Agent in Jind", link: "#" },
    { name: "Real Estate Agent in Kaithal", link: "#" },
    { name: "Real Estate Agent in Sirsa", link: "#" },
    { name: "Real Estate Agent in Faridabad", link: "#" },
    { name: "Real Estate Agent in Gurgaon", link: "#" },
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Kurukshetra", link: "#" },
    { name: "Real Estate Agent in Yamunanagar", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Ambala", link: "#" },
    { name: "Real Estate Agent in Jhajjar", link: "#" },
    { name: "Real Estate Agent in Panipat", link: "#" },
    { name: "Real Estate Agent in Sonepat", link: "#" },
    { name: "Real Estate Agent in Rewari", link: "#" },
    { name: "Real Estate Agent in Jind", link: "#" },
    { name: "Real Estate Agent in Kaithal", link: "#" },
    { name: "Real Estate Agent in Sirsa", link: "#" },
    { name: "Real Estate Agent in Faridabad", link: "#" },
    { name: "Real Estate Agent in Gurgaon", link: "#" },
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Kurukshetra", link: "#" },
    { name: "Real Estate Agent in Yamunanagar", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Ambala", link: "#" },
    { name: "Real Estate Agent in Jhajjar", link: "#" },
    { name: "Real Estate Agent in Panipat", link: "#" },
    { name: "Real Estate Agent in Sonepat", link: "#" },
    { name: "Real Estate Agent in Rewari", link: "#" },
    { name: "Real Estate Agent in Jind", link: "#" },
    { name: "Real Estate Agent in Kaithal", link: "#" },
    { name: "Real Estate Agent in Sirsa", link: "#" },
    { name: "Real Estate Agent in Faridabad", link: "#" },
    { name: "Real Estate Agent in Gurgaon", link: "#" },
    { name: "Real Estate Agent in Bhiwani", link: "#" },
    { name: "Real Estate Agent in Kurukshetra", link: "#" },
    { name: "Real Estate Agent in Yamunanagar", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
    { name: "Real Estate Agent in Palwal", link: "#" },
    { name: "Real Estate Agent in Karnal", link: "#" },
    { name: "Real Estate Agent in Rohtak", link: "#" },
    { name: "Real Estate Agent in Fatehabad", link: "#" },
    { name: "Real Estate Agent in Panchkula", link: "#" },
    { name: "Real Estate Agent in Charkhi Dadri", link: "#" },
  ]