export const aData = {
    1:{src:'/amenities/aerobicsRoom.webp',name:'Aerobics Room'},
    2:{src:'/amenities/airConditioning.webp',name:'Air Conditioning'},
    3:{src:'/amenities/amphiTheatre.webp',name:'Amphitheatre'},
    4:{src:'/amenities/artsCraft.webp',name:'Arts & Craft Studio'},
    5:{src:'/amenities/atm.webp',name:'ATM'},
    6:{src:'/amenities/badmintonCourt.webp',name:'Badminton Court'},
    7:{src:'/amenities/banquetHall.webp',name:'Banquet Hall'},
    8:{src:'/amenities/barLounge.webp',name:'Bar & Lounge'},
    9:{src:'/amenities/barbequePit.webp',name:'Barbeque Pit'},
    10:{src:'/amenities/cafeteria.webp',name:'Cafeteria/Food Court'},
    11:{src:'/amenities/carParking.webp',name:'Car Parking'},
    12:{src:'/amenities/carWash.webp',name:'Car Wash Area'},
    13:{src:'/amenities/cigarLounge.webp',name:'Cigar Lounge'},
    14:{src:'/amenities/clubHouse.webp',name:'Club House'},
    15:{src:'/amenities/coffeeLounge.webp',name:'Coffee Lounge'},
    16:{src:'/amenities/conciergeService.webp',name:'Concierge Service'},
    17:{src:'/amenities/conferenceRoom.webp',name:'Conference Room'},
    18:{src:'/amenities/crecheFacility.webp',name:'Creche Facility'},
    19:{src:'/amenities/cricketPitch.webp',name:'Cricket Pitch'},
    20:{src:'/amenities/cyclingTrack.webp',name:'Cycling Track'},
    21:{src:'/amenities/television.webp',name:'Television'},
    22:{src:'/amenities/earthquakeResistant.webp',name:'Earthquake Resistant'},
    23:{src:'/amenities/escalators.webp',name:'Escalators'},
    24:{src:'/amenities/fireFighting.webp',name:'Firefighting Equipment'},
    25:{src:'/amenities/garden.webp',name:'Garden'},
    26:{src:'/amenities/golfCourse.webp',name:'Golf Course'},
    27:{src:'/amenities/guestAccomodations.webp',name:'Guest Accomodation'},
    28:{src:'/amenities/gym.webp',name:'Gym'},
    29:{src:'/amenities/indoorGamesRoom.webp',name:'Indoor Games Room'},
    30:{src:'/amenities/intercomFacility.webp',name:'Intercom Facility'},
    31:{src:'/amenities/internet.webp',name:'Internet/Wifi'},
    32:{src:'/amenities/joggingTrack.webp',name:'Jogging Track'},
    33:{src:'/amenities/kidsPlayArea.webp',name:'Kids Play Area'},
    34:{src:'/amenities/laundry.webp',name:'Laundry'},
    35:{src:'/amenities/lift.webp',name:'Lift'},
    36:{src:'/amenities/maintenanceStaff.webp',name:'Maintenance Staff'},
    37:{src:'/amenities/medicalCare.webp',name:'Medical Centre'},
    38:{src:'/amenities/meditationArea.webp',name:'Meditation Area'},
    39:{src:'/amenities/miniTheatre.webp',name:'Mini Theatre'},
    40:{src:'/amenities/multiplexes.webp',name:'Multiplexes'},
    41:{src:'/amenities/Park.webp',name:'Park'},
    42:{src:'/amenities/pipedGas.webp',name:'Piped Gas'},
    43:{src:'/amenities/powerBackup.webp',name:'Power Backup'},
    44:{src:'/amenities/reversedParking.webp',name:'Reserved Parking'},
    45:{src:'/amenities/retailShops.webp',name:'Retail Shops'},
    46:{src:'/amenities/roWaterSystem.webp',name:'RO water systems'},
    47:{src:'/amenities/sauna.webp',name:'Sauna/Spa'},
    48:{src:'/amenities/security.webp',name:'Security(CCTV)'},
    49:{src:'/amenities/swimmingPool.webp',name:'Swimming Pool'},
    50:{src:'/amenities/tennisCourts.webp',name:'Tennis Courts'},
    51:{src:'/amenities/vastuFriendly.png',name:'Vastu Friendly'},
    52:{src:'/amenities/visitorParking.webp',name:'Visitor Parking'},
    53:{src:'/amenities/wasteDisposal.webp',name:'Waste Disposal'},
}