export const cardData = [
    {
      id: 1,
      title: "RESIDENTIAL PROPERTIES",
      imageUrl: "/homePage/option1 - Copy.jpg",
      links: [
        "Flats for Sale in New Delhi",
        "House for Sale in New Delhi",
        "Plots for Sale in New Delhi",
        "Villas for Sale in New Delhi",
        "Penthouse in New Delhi",
        "Ready To Move Flats in New Delhi",
        "House for Sale in Dwarka New Delhi",
        "House for Sale in Uttam Nagar New Delhi",
        "House for Sale in Janakpuri New Delhi",
        "House for Sale in Najafgarh New Delhi",
        "House for Sale in Vasant Vihar New Delhi",
        "House for Sale in Pitampura New Delhi",
        "Flats for Sale in Saket New Delhi",
        "Flats for Sale in Karol Bagh New Delhi",
        "Flats for Sale in Lajpat Nagar New Delhi",
        "Flats for Sale in Malviya Nagar New Delhi",
        "Flats for Sale in Dwarka Mor New Delhi",
        "Flats for Sale in Vasant Kunj New Delhi", 
      ],
    },
    {
      id: 2,
      title: "FLATS",
      imageUrl: "/homePage/option2.webp",
      links: [
        "Flats for Sale in New Delhi",
        "House for Sale in New Delhi",
        "Plots for Sale in New Delhi",
        "Villas for Sale in New Delhi",
        "Penthouse in New Delhi",
        "Ready To Move Flats in New Delhi",
        "1BHK Flats for Sale in New Delhi",
        "2BHK Flats for Sale in New Delhi",
        "3BHK Flats for Sale in New Delhi",
        "4BHK Flats for Sale in New Delhi",
        "5BHK Flats for Sale in New Delhi",
        "6BHK Flats for Sale in New Delhi",
        "Flats for Sale in Saket New Delhi",
        "Flats for Sale in Karol Bagh New Delhi",
        "Flats for Sale in Lajpat Nagar New Delhi",
        "Flats for Sale in Malviya Nagar New Delhi",
        "Flats for Sale in Dwarka Mor New Delhi",
        "Flats for Sale in Vasant Kunj New Delhi",
      ],
    },
    {
      id: 3,
      title: "COMMERCIAL PROPERTIES",
      imageUrl: "/homePage/option3.jpg",
      links: [
        "Flats for Sale in New Delhi",
        "House for Sale in New Delhi",
        "Plots for Sale in New Delhi",
        "Villas for Sale in New Delhi",
        "Penthouse in New Delhi",
        "Ready To Move Flats in New Delhi",
        "House for Sale in Dwarka New Delhi",
        "House for Sale in Uttam Nagar New Delhi",
        "House for Sale in Janakpuri New Delhi",
        "House for Sale in Najafgarh New Delhi",
        "House for Sale in Vasant Vihar New Delhi",
        "House for Sale in Pitampura New Delhi",
        "Flats for Sale in Saket New Delhi",
        "Flats for Sale in Karol Bagh New Delhi",
        "Flats for Sale in Lajpat Nagar New Delhi",
        "Flats for Sale in Malviya Nagar New Delhi",
        "Flats for Sale in Dwarka Mor New Delhi",
        "Flats for Sale in Vasant Kunj New Delhi",
      ],
    },

    {
      id: 4,
      title: "OFFICES",
      imageUrl: "/homePage/option4.webp",
      links: [
        "Commercial Space for Sale in New Delhi",
        "Office space for Sale in New Delhi",
        "Retail Space for Sale in New Delhi",
        "Villas for Sale in New Delhi",
        "Penthouse in New Delhi",
        "Ready To Move Flats in New Delhi",
        "House for Sale in Dwarka New Delhi",
        "House for Sale in Uttam Nagar New Delhi",
        "House for Sale in Janakpuri New Delhi",
        "House for Sale in Najafgarh New Delhi",
        "House for Sale in Vasant Vihar New Delhi",
        "House for Sale in Pitampura New Delhi",
        "Flats for Sale in Saket New Delhi",
        "Flats for Sale in Karol Bagh New Delhi",
        "Flats for Sale in Lajpat Nagar New Delhi",
        "Flats for Sale in Malviya Nagar New Delhi",
        "Flats for Sale in Dwarka Mor New Delhi",
        "Flats for Sale in Vasant Kunj New Delhi",
      ],
    
    },
  ];

